version: '3.3'

services:

 postgres:
   image: postgres:alpine

   volumes:
     - ./postgres/data:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: focus1234
     POSTGRES_DB: focusdb
   expose:
     - "5432"

 flaskapp:
   image: gmendoza97/focus-ssr:latest
   restart: always
   expose:
     - "5000"
   depends_on:
     - redis
     - postgres
   links:
     - redis
     - postgres
          
 nginx:
   image: nginx:latest
   restart: always
   ports:
     - "80:80"
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
     - flaskapp

 redis:
   image: redis:alpine
   expose:
     - "6379"